modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"
[[mods]]
    modId="ravenbrewscore"
    version="1.0.1"
    displayName="Raven Brews Core"
    logoFile="ravenBrewsCoreLogo.png"
    credits="Credits to me, TheWandererRaven, cheers."
    authors="TheWandererRaven"
    description='''
    This is the Core for the RavenCoffeeMod, so I can later work on similar mods instead of packing everything in the same mod.
    '''
[[dependencies.ravenbrewscore]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ravenbrewscore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"
